<?php

use Illuminate\Database\Seeder;

class DesignsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('designs')->delete();
        
        \DB::table('designs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Forever Love',
                'slug' => 'forever-love',
                'image' => 'a:1:{i:0;s:16:"SPDOUBHEART1.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Forever Heart pendant is silver plated.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 09:39:21',
                'updated_at' => '2017-08-06 23:00:04',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Sea Star',
                'slug' => 'sea-star',
                'image' => 'a:1:{i:0;s:18:"SPDOUBSTAR1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Sea Star pendant is silver plated.  The setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 09:50:37',
                'updated_at' => '2017-08-06 23:06:23',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Never Forget',
                'slug' => 'never-forget',
                'image' => 'a:1:{i:0;s:17:"SPELEPHANT-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Never Forget #33 pendant is silver plated.  This setting includes the pendant, a sterling silver chain and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:09:29',
                'updated_at' => '2017-08-06 23:02:02',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Celtic Swirl',
                'slug' => 'celtic-swirl',
                'image' => 'a:1:{i:0;s:16:"SPFLOWER1-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Celtic Swirl pendant is silver plated.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:10:22',
                'updated_at' => '2017-08-06 23:02:53',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Monkey Love',
                'slug' => 'monkey-love',
                'image' => 'a:3:{i:0;s:16:"1-MONKEY1-lg.png";i:1;s:13:"SPMONKEY1.JPG";i:2;s:13:"SPMONKEY1.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Monkey Love is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:11:07',
                'updated_at' => '2017-08-11 21:18:25',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'The Messenger',
                'slug' => 'the-messenger',
                'image' => 'a:1:{i:0;s:13:"SPOWL1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Messenger is a silver plated pendant.  This setting includes the pendant, a sterling silver chain and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:11:49',
                'updated_at' => '2017-08-06 23:04:41',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Paw Print',
                'slug' => 'paw-print',
                'image' => 'a:1:{i:0;s:12:"SSPAW-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Paw Print #30 is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:12:30',
                'updated_at' => '2017-08-06 23:05:37',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Shooting Star',
                'slug' => 'shooting-star',
                'image' => 'a:1:{i:0;s:14:"SPSTAR1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Shooting Star is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:17:29',
                'updated_at' => '2017-08-06 23:07:17',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Best Mom',
                'slug' => 'best-mom',
                'image' => 'a:1:{i:0;s:16:"SPBESTMOM-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Best Mom is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:27:17',
                'updated_at' => '2017-08-06 23:08:01',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Life\'s Anchor',
                'slug' => 'life-s-anchor',
                'image' => 'a:1:{i:0;s:15:"SPANCHOR-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Life\'s Anchor is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:28:21',
                'updated_at' => '2017-08-06 23:08:46',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Butterfly Kisses',
                'slug' => 'butterfly-kisses',
                'image' => 'a:1:{i:0;s:19:"SPBUTTERFLY2-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Butterfly Kisses is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:29:29',
                'updated_at' => '2017-08-06 23:09:38',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'order_id' => '42',
                'published' => 1,
                'name' => 'MIdnight Ride',
                'slug' => 'midnight-ride',
                'image' => 'a:4:{i:0;s:14:"1-carriage.jpg";i:1;s:12:"carriage.jpg";i:2;s:14:"carriage-2.jpg";i:3;s:28:"Pearl-Cage-Carriage-Open.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Midnight Ride is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:30:41',
                'updated_at' => '2017-08-12 01:55:03',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'The Sunflower',
                'slug' => 'the-sunflower',
                'image' => 'a:1:{i:0;s:19:"SPSUNFLOWER1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Sunflower is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:37:06',
                'updated_at' => '2017-08-06 23:11:20',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Dolphin\'s Cove',
                'slug' => 'dolphin-s-cove',
                'image' => 'a:1:{i:0;s:17:"SPDOLPHIN1-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Dolphin\'s Cove is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:37:33',
                'updated_at' => '2017-08-06 23:12:11',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Dole Whip',
                'slug' => 'dole-whip',
                'image' => 'a:2:{i:0;s:13:"pinnapple.jpg";i:1;s:18:"pineapplepearl.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Dole Whip is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:13:27',
                'updated_at' => '2017-08-12 06:05:06',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Rain Drop',
                'slug' => 'rain-dro',
                'image' => 'a:1:{i:0;s:19:"tear drop pearl.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Rain Drop is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:14:39',
                'updated_at' => '2017-08-12 03:05:03',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'The Lantern',
                'slug' => 'the-lantern',
                'image' => 'a:1:{i:0;s:8:"tube.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Lantern is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:15:32',
                'updated_at' => '2017-08-12 04:49:20',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Secret Garden',
                'slug' => 'secret-garden',
                'image' => 'a:1:{i:0;s:10:"flower.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Secret Garden is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:16:22',
                'updated_at' => '2017-08-12 03:05:54',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'The Lotus',
                'slug' => 'the-lotus',
                'image' => 'a:1:{i:0;s:11:"SSLOTUS.JPG";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Lotus is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:26:11',
                'updated_at' => '2017-08-12 03:09:06',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Queen of Hearts',
                'slug' => 'queen-of-hearts',
                'image' => 'a:1:{i:0;s:16:"double-heart.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Queen of Hearts is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:27:15',
                'updated_at' => '2017-08-12 03:52:38',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'order_id' => '07',
                'published' => 1,
                'name' => 'Never Forget',
                'slug' => 'never-forget',
                'image' => 'a:1:{i:0;s:12:"elephant.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Never Forget #07 is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:28:22',
                'updated_at' => '2017-08-12 02:57:22',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Infinity Wings',
                'slug' => 'infinity-wings',
                'image' => 'a:1:{i:0;s:11:"sswings.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Infinity Wings is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:33:41',
                'updated_at' => '2017-08-12 03:12:52',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Olympic Love',
                'slug' => 'olympic-love',
                'image' => 'a:1:{i:0;s:16:"circle-heart.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Olympic Love is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:34:30',
                'updated_at' => '2017-08-12 03:54:07',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Honu',
                'slug' => 'honu',
                'image' => 'a:3:{i:0;s:10:"turtle.jpg";i:1;s:12:"1-turtle.jpg";i:2;s:10:"turtle.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Honu is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:36:37',
                'updated_at' => '2017-08-12 04:00:55',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Luck of the Irish',
                'slug' => 'luck-of-the-irish',
                'image' => 'a:1:{i:0;s:12:"SSCLOVER.JPG";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Luck of the Irish is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:37:30',
                'updated_at' => '2017-08-12 03:10:02',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'French Twist',
                'slug' => 'french-twist',
                'image' => 'a:3:{i:0;s:11:"1-twist.jpg";i:1;s:9:"twist.jpg";i:2;s:9:"twist.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The French Twist is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:51:35',
                'updated_at' => '2017-08-12 02:06:01',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Minnie Mouse',
                'slug' => 'minnie-mouse',
                'image' => 'a:2:{i:0;s:12:"1-minnie.jpg";i:1;s:10:"minnie.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Minnie Mouse is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:53:45',
                'updated_at' => '2017-08-12 03:03:28',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Midnight Ride',
                'slug' => 'midnight-ride',
                'image' => 'a:1:{i:0;s:21:"princess carriage.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Midnight Ride #12 is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:54:58',
                'updated_at' => '2017-08-06 23:54:58',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'All My Love',
                'slug' => 'all-my-love',
                'image' => 'a:1:{i:0;s:12:"SP4HEART.JPG";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The All My Love is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:59:48',
                'updated_at' => '2017-08-07 00:05:32',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}