<?php

use Illuminate\Database\Seeder;

class DesignsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('designs')->delete();
        
        \DB::table('designs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'order_id' => '#39',
                'published' => 1,
                'name' => 'Forever Love',
                'slug' => 'forever-love',
                'image' => 'a:1:{i:0;s:16:"SPDOUBHEART1.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Forever Love Silver Plated Pendant #39',
                'details' => '<p>The Forever Love pendant is silver plated.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.  </p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 09:39:21',
                'updated_at' => '2017-08-22 19:46:22',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'order_id' => '#31',
                'published' => 1,
                'name' => 'Sea Star',
                'slug' => 'sea-star',
                'image' => 'a:1:{i:0;s:18:"SPDOUBSTAR1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Sea Star Pendant is Silver Plated #31.',
                'details' => '<p>The Sea Star pendant is silver plated. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 09:50:37',
                'updated_at' => '2017-08-14 02:20:35',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'order_id' => '#33',
                'published' => 1,
                'name' => 'Never Forget',
                'slug' => 'never-forget',
                'image' => 'a:1:{i:0;s:17:"SPELEPHANT-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Never Forget Silver Plated #33',
                'details' => '<p>The Never Forget is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening. &nbsp;</p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:09:29',
                'updated_at' => '2017-08-14 02:22:01',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'order_id' => '#37',
                'published' => 1,
                'name' => 'Celtic Swirl',
                'slug' => 'celtic-swirl',
                'image' => 'a:1:{i:0;s:16:"SPFLOWER1-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Celtin Swirl Silver Plated Pendant #37',
                'details' => '<p>The Celtic Swirl pendant is silver plated. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:10:22',
                'updated_at' => '2017-08-14 02:22:55',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'order_id' => '#38',
                'published' => 1,
                'name' => 'Monkey Love',
                'slug' => 'monkey-love',
                'image' => 'a:1:{i:0;s:13:"spmonkey1.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Monkey Love Silver Plated Setting #38.',
                'details' => '<p><br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:11:07',
                'updated_at' => '2017-08-22 23:48:10',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'order_id' => '#44',
                'published' => 1,
                'name' => 'The Messenger',
                'slug' => 'the-messenger',
                'image' => 'a:1:{i:0;s:13:"SPOWL1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Messenger Silver Plated Pendant #44.',
                'details' => '<p>The Messenger is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver chain and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:11:49',
                'updated_at' => '2017-08-14 02:39:21',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'order_id' => '#30',
                'published' => 1,
                'name' => 'Paw Print',
                'slug' => 'paw-print',
                'image' => 'a:1:{i:0;s:12:"SSPAW-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Paw Print Pendant Silver Plated #30.',
                'details' => '<p>The Paw Print #30 is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:12:30',
                'updated_at' => '2017-08-14 02:40:08',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'order_id' => '#36',
                'published' => 1,
                'name' => 'Shooting Star',
                'slug' => 'shooting-star',
                'image' => 'a:1:{i:0;s:14:"SPSTAR1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Shooting Star Silver Plated Pendant #36.',
                'details' => '<p>The Shooting Star is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 10:17:29',
                'updated_at' => '2017-08-14 02:40:55',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'order_id' => '#46',
                'published' => 1,
                'name' => 'Best Mom',
                'slug' => 'best-mom',
                'image' => 'a:1:{i:0;s:16:"SPBESTMOM-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Best Mom Silver Plated Pendant #46.',
                'details' => '<p>The Best Mom is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:27:17',
                'updated_at' => '2017-08-14 02:41:45',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'order_id' => '#40',
                'published' => 1,
                'name' => 'Life\'s Anchor',
                'slug' => 'life-s-anchor',
                'image' => 'a:1:{i:0;s:15:"SPANCHOR-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Life\'s Anchor Silver Plated Pendant #40.',
                'details' => '<p>The Life\'s Anchor is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:28:21',
                'updated_at' => '2017-08-14 02:48:46',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'order_id' => '#34',
                'published' => 1,
                'name' => 'Butterfly Kisses',
                'slug' => 'butterfly-kisses',
                'image' => 'a:1:{i:0;s:19:"SPBUTTERFLY2-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Butterfly Kisses Silver Plated Pendant #34.',
                'details' => '<p>The Butterfly Kisses is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:29:29',
                'updated_at' => '2017-08-14 02:49:25',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'order_id' => '#42',
                'published' => 1,
                'name' => 'MIdnight Ride',
                'slug' => 'midnight-ride',
                'image' => 'a:4:{i:0;s:14:"1-carriage.jpg";i:1;s:12:"carriage.jpg";i:2;s:14:"carriage-2.jpg";i:3;s:28:"Pearl-Cage-Carriage-Open.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Midnight Ride Silver Plated Pendant #42.',
                'details' => '<p>The Midnight Ride #42 is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:30:41',
                'updated_at' => '2017-08-14 02:50:15',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'order_id' => '#32',
                'published' => 1,
                'name' => 'The Sunflower',
                'slug' => 'the-sunflower',
                'image' => 'a:1:{i:0;s:19:"SPSUNFLOWER1-lg.png";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Sunflower Silver Plated Pendant #32.',
                'details' => '<p>The Sunflower is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:37:06',
                'updated_at' => '2017-08-14 02:50:52',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'order_id' => '#43',
                'published' => 1,
                'name' => 'Dolphin\'s Cove',
                'slug' => 'dolphin-s-cove',
                'image' => 'a:1:{i:0;s:17:"SPDOLPHIN1-lg.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Dolphin\'s Cove Silver Plated Pendant #43.',
                'details' => '<p>The Dolphin\'s Cove is a silver plated pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-05 22:37:33',
                'updated_at' => '2017-08-14 02:51:30',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'order_id' => '#1',
                'published' => 1,
                'name' => 'Dole Whip',
                'slug' => 'dole-whip',
                'image' => 'a:2:{i:0;s:13:"pinnapple.jpg";i:1;s:18:"pineapplepearl.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Dole Whip Sterling SIlver Pendant #1.',
                'details' => '<p>The Dole Whip is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:13:27',
                'updated_at' => '2017-08-22 23:54:20',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'order_id' => '#2',
                'published' => 1,
                'name' => 'Rain Drop',
                'slug' => 'rain-dro',
                'image' => 'a:1:{i:0;s:13:"rain-drop.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Rain Drop Sterling Silver Pendant #2.',
                'details' => '<p>The Rain Drop is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:14:39',
                'updated_at' => '2017-08-23 00:23:46',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'order_id' => '#3',
                'published' => 1,
                'name' => 'The Lantern',
                'slug' => 'the-lantern',
                'image' => 'a:1:{i:0;s:8:"tube.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Lantern Sterling Silver Pendant #3.',
                'details' => '<p>The Lantern is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.</p><p>**This pendant will hold up to 4 pearls.   This setting and price includes 1 oyster opening.  Additional openings can be purchased at any time.**</p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:15:32',
                'updated_at' => '2017-08-22 23:56:15',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'order_id' => '#4',
                'published' => 1,
                'name' => 'Secret Garden',
                'slug' => 'secret-garden',
                'image' => 'a:1:{i:0;s:10:"flower.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Secret Garden Sterling SIlver Pendant #4.',
                'details' => '<p>The Secret Garden is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:16:22',
                'updated_at' => '2017-08-22 23:56:29',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'order_id' => '#5',
                'published' => 1,
                'name' => 'The Lotus',
                'slug' => 'the-lotus',
                'image' => 'a:1:{i:0;s:11:"SSLOTUS.JPG";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Lotus Sterling Silver Pendant #5.',
                'details' => '<p>The Lotus is a sterling silver pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:26:11',
                'updated_at' => '2017-08-14 02:55:29',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'order_id' => '#6',
                'published' => 1,
                'name' => 'Queen of Hearts',
                'slug' => 'queen-of-hearts',
                'image' => 'a:1:{i:0;s:16:"double-heart.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Queen of Hearts Sterling Silver Pendant #6.',
                'details' => '<p>The Queen of Hearts is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:27:15',
                'updated_at' => '2017-08-23 00:22:36',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'order_id' => '#7',
                'published' => 1,
                'name' => 'Never Forget',
                'slug' => 'never-forget',
                'image' => 'a:1:{i:0;s:14:"1-elephant.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Never Forget Sterling Silver Pendant #7.',
                'details' => '<p>The Never Forget #7 is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:28:22',
                'updated_at' => '2017-08-23 00:26:22',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'order_id' => '#8',
                'published' => 1,
                'name' => 'Infinity Wings',
                'slug' => 'infinity-wings',
                'image' => 'a:1:{i:0;s:18:"infinity-wings.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Infinity Wings Sterling Silver Pendant #8.',
                'details' => '<p>The Infinity Wings is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:33:41',
                'updated_at' => '2017-08-23 00:25:55',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'order_id' => '#9',
                'published' => 1,
                'name' => 'Olympic Love',
                'slug' => 'olympic-love',
                'image' => 'a:1:{i:0;s:16:"cilcle-heart.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Olympic Love Sterling Silver Pendant #9.',
                'details' => '<p>The Olympic Love is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:34:30',
                'updated_at' => '2017-08-23 00:22:23',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'order_id' => '#10',
                'published' => 1,
                'name' => 'Honu',
                'slug' => 'honu',
                'image' => 'a:1:{i:0;s:10:"turtle.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Honu Sterling Silver Pendant #10.',
                'details' => '<p>The Honu is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:36:37',
                'updated_at' => '2017-08-22 23:53:15',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'order_id' => NULL,
                'published' => 1,
                'name' => 'Luck of the Irish',
                'slug' => 'luck-of-the-irish',
                'image' => 'a:1:{i:0;s:10:"clover.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'The Luck of the Irish is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.',
                'details' => NULL,
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:37:30',
                'updated_at' => '2017-08-22 23:56:43',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'order_id' => '#13',
                'published' => 1,
                'name' => 'French Twist',
                'slug' => 'french-twist',
                'image' => 'a:3:{i:0;s:11:"1-twist.jpg";i:1;s:9:"twist.jpg";i:2;s:9:"twist.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'French Twist Sterling Silver Pendant #13.',
                'details' => '<p>The French Twist is a sterling silver pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:51:35',
                'updated_at' => '2017-08-14 03:04:03',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'order_id' => '#14',
                'published' => 1,
                'name' => 'Minnie Mouse',
                'slug' => 'minnie-mouse',
                'image' => 'a:2:{i:0;s:12:"1-minnie.jpg";i:1;s:10:"minnie.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Minnie Mouse Sterling Silver Pendant #14.',
                'details' => '<p>The Minnie Mouse is a sterling silver pendant. &nbsp;This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:53:45',
                'updated_at' => '2017-08-14 03:04:43',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'order_id' => '#12',
                'published' => 1,
                'name' => 'Midnight Ride',
                'slug' => 'midnight-ride',
                'image' => 'a:1:{i:0;s:14:"carriage-2.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'Midnight Ride Sterling Silver Pendant #12.',
                'details' => '<p>The Midnight Ride is a sterling silver pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '45.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:54:58',
                'updated_at' => '2017-08-22 23:44:18',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'order_id' => '#41',
                'published' => 1,
                'name' => 'All My Love',
                'slug' => 'all-my-love',
                'image' => 'a:1:{i:0;s:15:"all-my-love.jpg";}',
                'button_code' => 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6UCU5V4HZZDGQ',
                'short_details' => 'All My Love Silver Plated Pendant #41.',
                'details' => '<p>The All My Love is a silver plated pendant.  This setting includes the pendant, a sterling silver necklace and 1 oyster opening.<br></p>',
                'price' => '35.00',
                'availability' => 'Available',
                'created_at' => '2017-08-06 23:59:48',
                'updated_at' => '2017-08-23 00:28:54',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}